stages:
  - deploy

deploy:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@44.208.22.250 "sudo rm -rf /var/www/html/*"
    - scp -o StrictHostKeyChecking=no index.html ubuntu@44.208.22.250:/var/www/html/
    - ssh -o StrictHostKeyChecking=no ubuntu@44.208.22.250> "sudo systemctl restart apache2"
  only:
    - main
