name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy index.html to EC2
      run: |
        scp -o StrictHostKeyChecking=no index.html ubuntu@52.91.46.108:/tmp/index.html
        ssh -o StrictHostKeyChecking=no ubuntu@52.91.46.108 'sudo mv /tmp/index.html /var/www/html/index.html && sudo systemctl restart nginx'
